"""
Schemas the AI service's output must conform to. Per spec §29/§47,
AI output is never trusted blindly — scores are computed by a
transparent rule-based layer, and only the *explanation* text is
generated by the LLM and validated/sanitized here.
"""
from pydantic import BaseModel, Field, field_validator


class MatchAnalysis(BaseModel):
    match_score: int = Field(ge=0, le=100)
    eligibility_score: int = Field(ge=0, le=100)
    skills_score: int = Field(ge=0, le=100)
    education_score: int = Field(ge=0, le=100)
    experience_score: int = Field(ge=0, le=100)
    matched_skills: list[str] = []
    missing_skills: list[str] = []
    explanation: str
    eligibility_notes: str

    @field_validator("explanation", "eligibility_notes")
    @classmethod
    def not_absolute(cls, v: str) -> str:
        # Basic guardrail: strip overconfident absolute claims per spec §31.
        replacements = {
            "you are definitely eligible": "you appear to meet the listed eligibility criteria",
            "you will definitely get": "this may improve your chances of getting",
            "guaranteed": "likely",
        }
        lowered = v.lower()
        for bad, good in replacements.items():
            if bad in lowered:
                idx = lowered.find(bad)
                v = v[:idx] + good + v[idx + len(bad):]
                lowered = v.lower()
        return v

class ResumeEducationItem(BaseModel):
    institution: str = ""
    degree: str = ""
    field_of_study: str = ""
    start_year: int | None = None
    end_year: int | None = None


class ResumeExperienceItem(BaseModel):
    company: str = ""
    title: str = ""
    description: str = ""


class ResumeProjectItem(BaseModel):
    title: str = ""
    description: str = ""


class ResumeCertificationItem(BaseModel):
    name: str = ""
    issuer: str = ""


class ResumeStructuredData(BaseModel):
    """Output of AI Resume -> Profile parsing (spec §14). This is a PREVIEW
    only — nothing here is saved to the profile until the user reviews and
    explicitly confirms each field, per the human-in-the-loop requirement."""
    full_name: str = ""
    email: str = ""
    headline: str = ""
    bio: str = ""
    skills: list[str] = []
    education: list[ResumeEducationItem] = []
    experience: list[ResumeExperienceItem] = []
    projects: list[ResumeProjectItem] = []
    certifications: list[ResumeCertificationItem] = []


class JobAnalysis(BaseModel):
    """Output of the AI Job Description Analyzer (spec §18)."""
    required_skills: list[str] = []
    preferred_skills: list[str] = []
    education_requirement: str = ""
    experience_requirement: str = ""
    responsibilities: list[str] = []
    technical_stack: list[str] = []
    soft_skills: list[str] = []
    estimated_difficulty: str = ""
    key_notes: str = ""


class CareerAssistantResponse(BaseModel):
    """Output of the AI Career Assistant (spec §17)."""
    answer: str
    suggested_next_steps: list[str] = []


class PostAssistantResponse(BaseModel):
    """Output of the AI Post Assistant (spec §15)."""
    revised_content: str
    suggested_title: str = ""
    suggested_hashtags: list[str] = []
